config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:show]

  post 'logins/create'
  get 'logins/new'
  get 'sessions/create'
  delete 'sessions/destroy'

  resources :comedies
  resources :search_results, only: :index

  namespace :comedy do
    resources :thumbnails, only: [:index]
  end

  resources :videos, only: :index
  resources :images, only: :index

  root 'comedies#index'
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    unless current_user.anonymous?
      redirect_to root_path, notice: 'Již jsi přihlášný'
    end
  end

  def create
    user = User.find_or_create_by!(email: params[:email]) do |user|
      user.name = 'tomáš'
    end
    user.update!(login_token: SecureRandom.urlsafe_base64, login_token_valid_until: Time.now + 15.minutes)

    LoginMailer.login_link(user).deliver

    redirect_to root_path, notice: 'Pro přihlášení klikni na link, který ti byl právě zaslán na email.'
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h2><strong>Přihlášení</strong></h2>

<%= form_tag logins_create_path do %>
  <fieldset class='form-group'>
    <%= label_tag 'Přihlášení', nil, class: 'sr-only', for: 'email' %>
    <div class="input-group">
      <%= text_field_tag 'email', nil, class: 'form-control', placeholder: 'Vyplň email na který ti bude zaslán přihlašovací link', required: true %>

      <span class="input-group-btn">
        <%= button_tag 'Přihlásit', class: "btn btn-success-outline" %>
      </span>
    </div>

  </fieldset>
<% end %>

<%= image_tag 'happy_patrick_big.gif', class: 'img-fluid center-block' %>