config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:show]

  post 'logins/create'
  get 'logins/new'
  get 'sessions/create'
  delete 'sessions/destroy'

  resources :comedies
  resources :search_results, only: :index

  namespace :comedy do
    resources :thumbnails, only: [:index]
  end

  resources :videos, only: :index
  resources :images, only: :index

  root 'comedies#index'
end

app/models/comedy.rb
class Comedy < ApplicationRecord
  acts_as_taggable

  has_one :image,
    dependent: :destroy

  has_one :video,
    dependent: :destroy

  validates :text,
    presence: true,
    length: { minimum: 100 }

  def self.title_search(title)
    where("cz_title LIKE ?", "%#{title}%").or(where("en_title LIKE ?", "%#{title}%"))
  end

  def self.next_by_id(id)
    where(["id > ?", id]).first
  end

  def self.previous_by_id(id)
    where(["id < ?", id]).last
  end

  def self.random(count = 5)
    order("RANDOM()").limit(count)
  end

  def bilingual_title
    [ cz_title, en_title ].select(&:present?).join(' - ')
  end

  def to_s
    bilingual_title
  end
end

app/models/comedy_form.rb
class ComedyForm
  include ActiveModel::Model

  attr_accessor :comedy

  delegate :cz_title, :cz_title=, :en_title, :en_title=, :text, :text=, :tag_list, :tag_list=, to: :comedy
  delegate :title, :title=, :image, :image=, to: :image, prefix: true
  delegate :title, :title=, to: :video, prefix: true
  delegate :uri, :uri=, to: :youtube_link, prefix: true

  def save
    if comedy.valid? && image.valid? && video.valid? && youtube_link.valid?
      comedy.save &&
        image.save &&
        video.save &&
        youtube_link.update(linker_type: 'Video', linker_id: video.id)
    end
  end

  def comedy
    @comedy ||= Comedy.new
  end

  def image
    @image ||= comedy.image || comedy.build_image
  end

  def video
    @video ||= comedy.video || comedy.build_video
  end

  def youtube_link
    @youtube_link ||= video.youtube_link || video.build_youtube_link
  end
end

app/controllers/comedies_controller.rb
class ComediesController < ApplicationController
  before_action :restrict_only_admins, only: [:new, :create]

  def show
    @comedy          = Comedy.find(params[:id])
    @next_comedy     = Comedy.next_by_id(@comedy.id)
    @previous_comedy = Comedy.previous_by_id(@comedy.id)
  end

  def index
    @comedies = Comedy.all.includes(:image).order(created_at: :desc).page(params[:page]).per(5)

    respond_to do |format|
      format.html do |html|
        html.desktop do
          @comedies = @comedies.includes(:tags)
        end

        html.tablet do
          @comedies = @comedies.includes(:tags)
        end
      end
    end
  end

  def new
    @comedy_form = ComedyForm.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  def create
    @comedy_form = ComedyForm.new(permitted_params)

    if @comedy_form.save
      redirect_to comedies_path
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :new
    end
  end

  def edit
    comedy = Comedy.find(params[:id])
    @comedy_form = ComedyForm.new(comedy: comedy)
    @tags = ActsAsTaggableOn::Tag.all
  end

  def update
    comedy = Comedy.find(params[:id])
    @comedy_form = ComedyForm.new(comedy: comedy)
    @comedy_form.assign_attributes(permitted_params)

    if @comedy_form.save
      redirect_to comedy_path(comedy)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :edit
    end
  end

  private

  def permitted_params
    params.require(:comedy_form).permit(:cz_title, :en_title, :text, :tag_list, :image_title, :video_title, :youtube_link_uri, :image_image)
  end
end

app/controllers/comedy/thumbnails_controller.rb
class Comedy::ThumbnailsController < ApplicationController
  def index
    @comedies = Comedy.order(:cz_title)
  end
end

app/views/comedies/_form.html.erb
<% if @comedy_form.comedy.errors.present? %>
  <b>Chyby u komedie</b>
  <% @comedy_form.comedy.errors.full_messages.each do |error| %>
    <p class='text-danger'><%= error %></p>
  <% end %>
<% end %>

<% if @comedy_form.image.errors.present? %>
  <b>Chyby u obrazku</b>
  <% @comedy_form.image.errors.full_messages.each do |error| %>
    <p class='text-danger'><%= error %></p>
  <% end %>
<% end %>

<% if @comedy_form.video.errors.present? %>
  <b>Chyby u videa</b>
  <% @comedy_form.video.errors.full_messages.each do |error| %>
    <p class='text-danger'><%= error %></p>
  <% end %>
<% end %>

<% if @comedy_form.youtube_link.errors.present? %>
  <b>Chyby u Youtube linku</b>
  <% @comedy_form.youtube_link.errors.full_messages.each do |error| %>
    <p class='text-danger'><%= error %></p>
  <% end %>
<% end %>

<%= form_for @comedy_form, form_options do |f| %>
  <h2>Komedie</h2>

  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.label :cz_title %>
      <%= f.text_field :cz_title, class: 'form-control' %>
    </div>

    <div class="col-sm-6">
      <%= f.label :en_title %>
      <%= f.text_field :en_title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: 'form-control', value: @comedy_form.tag_list.join(',') %>

    <small class="form-text text-muted">
      <%= @tags.map(&:name).join ',' %>
    </small>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: 'form-control' %>
  </div>

  <hr>
  <h2>Obrázek</h2>

  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.label :image_title %>
      <%= f.text_field :image_title, class: 'form-control' %>
    </div>

    <div class="col-sm-6">
      <%= f.label :image_image %>
      <%= f.file_field :image_image, class: 'form-control' %>
    </div>
  </div>

  <hr>
  <h2>Video</h2>

  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.label :video_title %>
      <%= f.text_field :video_title, class: 'form-control' %>
    </div>

    <div class="col-sm-6">
      <%= f.label :youtube_link_uri %>
      <%= f.text_field :youtube_link_uri, class: 'form-control' %>
    </div>
  </div>

  <%= f.button "Vytvořit" %>
<% end %>

app/views/comedies/edit.html.erb
<h1>Úprava komedie</h1>

<%= render 'form', form_options: { url: comedy_path(@comedy_form.comedy), method: :patch } %>

app/views/comedies/index.html+phone.erb
<div>
  <% @comedies.each do |comedy| %>
    <article>
      <h1><%= link_to comedy.bilingual_title, comedy_path(comedy) %></h1>

      <div class="entry-body">
        <%= image_tag comedy.image.image_url, class: 'img-fluid' %>

        <p class="comedy-description">
          <%= truncate(comedy.text, length: 200) %>
          <strong>
            <%= link_to 'Číst dále', comedy_path(comedy) %>
          </strong>
        </p>
      </div>
    </article>
  <% end %>

  <%= paginate @comedies %>
</div>

app/views/comedies/index.html+tablet.erb
<div>
  <% @comedies.each do |comedy| %>
    <article>
      <h1><strong><%= link_to comedy.bilingual_title, comedy_path(comedy) %></strong></h1>

      <small>
        <%= l(comedy.created_at) %>
        |
        <% comedy.tag_list.each do |tag| %>
          <%= tag_with_link(tag) %>
        <% end %>
      </small>

      <div class="entry-body">
        <%= image_tag comedy.image.image_url, class: 'img-fluid' %>

        <p class="comedy-description">
          <%= truncate(comedy.text, length: 200) %>
          <strong>
            <%= link_to 'Číst dále', comedy_path(comedy) %>
          </strong>
        </p>
      </div>
    </article>
  <% end %>

  <%= paginate @comedies %>
</div>

app/views/comedies/index.html.erb
<div>
  <% @comedies.each do |comedy| %>
    <article>
      <h1><%= link_to comedy.bilingual_title, comedy_path(comedy) %></h1>

      <div class="entry-body">
        <div class="row">
          <div class="col-xl-8">
            <% if comedy.image.present? && comedy.image.image_url.present? %>
              <%= image_tag(comedy.image.image_url, class: 'img-fluid') %>
            <% end %>
          </div>

          <div class="col-xl-4 no-left-gutter">
            Přidáno <%= l(comedy.created_at) %>

            <% comedy.tag_list.each do |tag| %>
              <%= tag_with_link(tag) %>
            <% end %>

            <% if current_user.admin? %>
              <%= link_to 'Upravit', edit_comedy_path(comedy) %>
            <% end %>
          </div>
        </div>

        <p>
          <%= truncate(comedy.text, length: 200) %>
          <strong>
            <%= link_to 'Číst dále', comedy_path(comedy) %>
          </strong>
        </p>
      </div>
    </article>
  <% end %>

  <%= paginate @comedies %>
</div>

app/views/comedies/list.html.erb
<div id="content" class="narrowcolumn">
  <div>
    <h3>Abecední seznam komedií</h3>
    <div class="comedies-list">
      <ul>
        <% @comedies.each do |comedy| %>
          <li><%= link_to comedy.bilingual_title, comedy_path(comedy) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/comedies/new.html.erb
<h1>Nová komedie</h1>

<%= render 'form', form_options: { url: comedies_path, method: :post } %>

app/views/comedies/show.html+phone.erb
<article>
  <h1><%= @comedy.bilingual_title %></h1>

  <div class="entry-body">
    <%= image_tag @comedy.image.image_url, class: 'img-fluid' %>

    <p><%= raw markdown.render(@comedy.text) %></p>

    <h2>Trailer</h2>
    <div class="entry-body embed-responsive embed-responsive-16by9">
      <%= video_iframe(@comedy.video)  %>
    </div>
  </div>

  <div>
    <% if @next_comedy %>
      <%= link_to(" ←   #{@next_comedy.bilingual_title}", comedy_path(@next_comedy), class: 'pull-left') %>
    <% end %>

    <% if @previous_comedy %>
      <%= link_to(" #{@previous_comedy.bilingual_title} → ", comedy_path(@previous_comedy), class: 'pull-right') %>
    <% end %>
  </div>
</article>

app/views/comedies/show.html+tablet.erb
<article>
  <h1><%= @comedy.bilingual_title %></h1>

  <small>
    <%= l(@comedy.created_at) %>
    |
    <% @comedy.tag_list.each do |tag| %>
      <%= tag_with_link(tag) %>
    <% end %>
  </small>

  <div class="entry-body">
    <%= image_tag @comedy.image.image_url, class: 'img-fluid' %>

    <p><%= raw markdown.render(@comedy.text) %></p>

    <h2>Trailer</h2>
    <div class="entry-body embed-responsive embed-responsive-16by9">
      <%= video_iframe(@comedy.video)  %>
    </div>
  </div>

  <div>
    <% if @next_comedy %>
      <%= link_to(" ←   #{@next_comedy.bilingual_title}", comedy_path(@next_comedy), class: 'pull-left') %>
    <% end %>

    <% if @previous_comedy %>
      <%= link_to(" #{@previous_comedy.bilingual_title} → ", comedy_path(@previous_comedy), class: 'pull-right') %>
    <% end %>
  </div>
</article>

app/views/comedies/show.html.erb
<article>
  <h1><%= @comedy.bilingual_title %></h1>

  <div class="entry-body">
    <div class="row">
      <div class="col-xl-8">
        <% if @comedy.image.present? && @comedy.image.image_url.present? %>
          <%= image_tag @comedy.image.image_url, class: 'img-fluid' %>
        <% end %>
      </div>

      <div class="col-xl-4 no-left-gutter">
        Přidáno <%= l(@comedy.created_at) %>

        <% @comedy.tag_list.each do |tag| %>
          <%= tag_with_link(tag) %>
        <% end %>

        <% if current_user.admin? %>
          <%= link_to 'Upravit', edit_comedy_path(@comedy) %>
        <% end %>
      </div>
    </div>

    <p><%= raw markdown.render(@comedy.text) %></p>

    <h2>Trailer</h2>
    <div class="entry-body embed-responsive embed-responsive-16by9">
      <%= video_iframe(@comedy.video)  %>
    </div>
  </div>


  <div>
    <% if @next_comedy %>
      <%= link_to(" ←   #{@next_comedy.bilingual_title}", comedy_path(@next_comedy), class: 'pull-left') %>
    <% end %>

    <% if @previous_comedy %>
      <%= link_to(" #{@previous_comedy.bilingual_title} → ", comedy_path(@previous_comedy), class: 'pull-right') %>
    <% end %>
  </div>
</article>