config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:show]

  post 'logins/create'
  get 'logins/new'
  get 'sessions/create'
  delete 'sessions/destroy'

  resources :comedies
  resources :search_results, only: :index

  namespace :comedy do
    resources :thumbnails, only: [:index]
  end

  resources :videos, only: :index
  resources :images, only: :index

  root 'comedies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comedy.rb
class Comedy < ApplicationRecord
  acts_as_taggable

  has_one :image,
    dependent: :destroy

  has_one :video,
    dependent: :destroy

  validates :text,
    presence: true,
    length: { minimum: 100 }

  def self.title_search(title)
    where("cz_title LIKE ?", "%#{title}%").or(where("en_title LIKE ?", "%#{title}%"))
  end

  def self.next_by_id(id)
    where(["id > ?", id]).first
  end

  def self.previous_by_id(id)
    where(["id < ?", id]).last
  end

  def self.random(count = 5)
    order("RANDOM()").limit(count)
  end

  def bilingual_title
    [ cz_title, en_title ].select(&:present?).join(' - ')
  end

  def to_s
    bilingual_title
  end
end

app/models/comedy_comment.rb
class ComedyComment < ApplicationRecord
  belongs_to :user
  belongs_to :comedy
end

app/models/comedy_form.rb
class ComedyForm
  include ActiveModel::Model

  attr_accessor :comedy

  delegate :cz_title, :cz_title=, :en_title, :en_title=, :text, :text=, :tag_list, :tag_list=, to: :comedy
  delegate :title, :title=, :image, :image=, to: :image, prefix: true
  delegate :title, :title=, to: :video, prefix: true
  delegate :uri, :uri=, to: :youtube_link, prefix: true

  def save
    if comedy.valid? && image.valid? && video.valid? && youtube_link.valid?
      comedy.save &&
        image.save &&
        video.save &&
        youtube_link.update(linker_type: 'Video', linker_id: video.id)
    end
  end

  def comedy
    @comedy ||= Comedy.new
  end

  def image
    @image ||= comedy.image || comedy.build_image
  end

  def video
    @video ||= comedy.video || comedy.build_video
  end

  def youtube_link
    @youtube_link ||= video.youtube_link || video.build_youtube_link
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :comedy

  validates :title,
    presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :uri,
    presence: true

  def o_uri
    URI(read_attribute(:uri) || 'ahoj' )
  end

  def method_missing(method, *args, &block)
    if o_uri.respond_to?(method)
      o_uri.send(method)
    else
      super
    end
  end
end

app/models/null_user.rb
class NullUser
  def name
    'Anonymni uzivatel'
  end

  def admin?
    false
  end

  def anonymous?
    true
  end

  def id
    nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  ADMIN_EMAIL = 'pdonat@seznam.cz'

  def admin?
    email == ADMIN_EMAIL
  end

  def anonymous?
    false
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :comedy

  has_one :youtube_link,
    as: :linker,
    dependent: :destroy

  validates :title,
    presence: true
end

app/models/youtube_link.rb
class YoutubeLink < Link
  belongs_to :linker,
    polymorphic: true
end

app/controllers/comedies_controller.rb
class ComediesController < ApplicationController
  before_action :restrict_only_admins, only: [:new, :create]

  def show
    @comedy          = Comedy.find(params[:id])
    @next_comedy     = Comedy.next_by_id(@comedy.id)
    @previous_comedy = Comedy.previous_by_id(@comedy.id)
  end

  def index
    @comedies = Comedy.all.includes(:image).order(created_at: :desc).page(params[:page]).per(5)

    respond_to do |format|
      format.html do |html|
        html.desktop do
          @comedies = @comedies.includes(:tags)
        end

        html.tablet do
          @comedies = @comedies.includes(:tags)
        end
      end
    end
  end

  def new
    @comedy_form = ComedyForm.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  def create
    @comedy_form = ComedyForm.new(permitted_params)

    if @comedy_form.save
      redirect_to comedies_path
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :new
    end
  end

  def edit
    comedy = Comedy.find(params[:id])
    @comedy_form = ComedyForm.new(comedy: comedy)
    @tags = ActsAsTaggableOn::Tag.all
  end

  def update
    comedy = Comedy.find(params[:id])
    @comedy_form = ComedyForm.new(comedy: comedy)
    @comedy_form.assign_attributes(permitted_params)

    if @comedy_form.save
      redirect_to comedy_path(comedy)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :edit
    end
  end

  private

  def permitted_params
    params.require(:comedy_form).permit(:cz_title, :en_title, :text, :tag_list, :image_title, :video_title, :youtube_link_uri, :image_image)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    unless current_user.anonymous?
      redirect_to root_path, notice: 'Již jsi přihlášný'
    end
  end

  def create
    user = User.find_or_create_by!(email: params[:email]) do |user|
      user.name = 'tomáš'
    end
    user.update!(login_token: SecureRandom.urlsafe_base64, login_token_valid_until: Time.now + 15.minutes)

    LoginMailer.login_link(user).deliver

    redirect_to root_path, notice: 'Pro přihlášení klikni na link, který ti byl právě zaslán na email.'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.where(login_token: params[:token]).where('login_token_valid_until > ?', Time.now).first

    if user
      unless user.admin?
        redirect_to root_path, alert: 'Přihlášení se nezdařilo. Zatím funguje přihlašování pouze pro adminy.'
        return
      end

      user.update!(login_token: nil, login_token_valid_until: 1.year.ago)

      self.current_user = user
      redirect_to root_path
    else
      redirect_to root_path, alert: 'Přihlášení se nezdařilo. Nejspíš jsi použil starý přihlašovací link. Zkus vygenerovat nový.'
    end
  end

  def destroy
    self.current_user = NullUser.new
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown
    Redcarpet::Markdown.new(renderer, {})
  end

  def video_iframe(video)
    content_tag(:iframe, nil, { src: video.youtube_link.uri,
                                height: 281,
                                width: 500,
                                allowfullscreen: '',
                                frameborder: 0 })
  end

  def tag_with_link(tag)
    content_tag :span, class: "badge badge-pill badge-default" do
      link_to tag, search_results_path(search_term: tag)
    end
  end

  def alert_css_class(key)
    { "notice" => 'success',
      "alert" => 'danger'
    }.fetch(key, 'success')
  end

  private

  def renderer
    @renderer ||= Redcarpet::Render::HTML.new({})
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <meta name='description' content='Pravidelně aktualizovaný seznam českých a zahraničních komedií.'>
    <title>Výběr z těch nejbláznivějších a nejzábavnějších komedií.</title>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <div id="header">
      <nav class="navbar">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo_small3.png', class: 'img-fluid' %>
        <% end %>

        <ul class='nav navbar-nav navbar-right'>
          <li class="nav-item"><%= link_to 'Abeceda', comedy_thumbnails_path %></li>
          <li class="nav-item"><%= link_to 'Plakáty', images_path %></li>
          <li class="nav-item"><%= link_to 'Videa', videos_path %></li>
        </ul>
      </nav>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12 blog-main">
          <%= yield %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <div id="footer">
            <p>
              © 2016 <a href="http://imagineanything.cz">Imagine Anything</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <meta name='description' content='Pravidelně aktualizovaný seznam českých a zahraničních komedií.'>
    <title>Výběr z těch nejbláznivějších a nejzábavnějších komedií.</title>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <div id="header">
      <div class="pink-line">
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-7 blog-main">
          <div class="row">
            <div class="col-sm-12">
              <% flash.each do |type, message| %>
                <div class="alert alert-<%= alert_css_class(type) %>" role="alert">
                  <%= message %>
                </div>
              <% end %>

              <%= yield %>
            </div>
          </div>
        </div>

        <div class="col-sm-5 blog-sidebar">
          <div id="sidebar">
            <div id="logo">
              <%= link_to root_path do %>
                <%= image_tag 'logo2.png', class: 'img-fluid' %>
              <% end %>
            </div>

            <h1>Vyhledávání</h1>
            <div class="search">
              <form action="/search_results" method="get">
                <label class="sr-only" for="search_term">Vyhledávání</label>
                <div class="input-group">
                  <input class="form-control" type="text" name="search_term" id="search_term" placeholder="Název, část textu, tag..." value="<%= params[:search_term] %>">

                  <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit">Hledat</button>
                  </span>
                </div>
              </form>
            </div>

            <div class="sidebar-menu">
              <h1>Menu</h1>
              <ul class="list-unstyled menu-list">
                <li><%= link_to 'Domů', root_path %></li>
                <li><%= link_to 'Abecední seznam Komedií', comedy_thumbnails_path %></li>
                <li><%= link_to 'Plakáty', images_path %></li>
                <li><%= link_to 'Trailery', videos_path %></li>

                <% if current_user.present? && current_user.admin? %>
                  <li><small><%= link_to 'Nová komedie', new_comedy_path %></small></li>
                <% end %>

                <% if current_user.present? && !current_user.anonymous? %>
                  <li><small><%= link_to 'Uživatelský účet', user_path %></small></li>
                  <li><small><%= link_to 'Odhlásit', sessions_destroy_path, method: :delete %></small></li>
                <% end %>
              </ul>
            </div>

            <h1>Náhodné komedie</h1>
            <ul class="list-unstyled menu-list">
              <% @random_comedies.each do |comedy| %>
                <li><%= link_to comedy.bilingual_title, comedy_path(comedy) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <div id="footer">
            <p>
              © 2016 <a href="http://imagineanything.cz">Imagine Anything</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>